# /mosquitto/config/mosquitto.conf
listener 8883
protocol mqtt

# TLS Configuration
cafile /mosquitto/certs/ca.cert.pem
certfile /mosquitto/certs/broker.cert.pem
keyfile /mosquitto/private/broker.key.pem

require_certificate true
tls_version tlsv1.2

use_identity_as_username true